import Footer from "@/components/footer/Footer"
import Navbar from "@/components/navbar/Navbar"
import { Container } from "@chakra-ui/react"
import Head from "next/head"
import React from "react"
import styles from "./layout.module.css"

const Layout = ({ children }: {children: React.ReactNode}) => {
  return (
    <div className={styles.app_container}>
      <Head>
        <title>Cryptoverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./cryptocurrency.png" />
      </Head>
      <Navbar />
      <Container flexGrow={1} maxW="container.xl" paddingBlock={4} >
        {children}
      </Container>
      <Footer />
    </div>
  )
}

export default Layout